name: GitHub Actions Build and Deploy Demo
on:
  push:
    branches:
      - main
permissions:
  contents: write
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      # - name: Checkout
      #   uses: actions/checkout@master

      - name: test Val
        env:
          HELLO: ${{vars.STR}}
        run: echo $HELLO && echo $CI

      - name: test Sec
        run: echo ${{ secrets.HELLO }}

      - name: test HEllo
        if: ${{vars.STR == 'HELLO WORLD'}}
        run: echo HEllo world 
      # - name: Install And Build
      #   run: npm install && npm run build

      # - name: Deploy
      #   uses: JamesIves/github-pages-deploy-action@v4
      #   with:
      #     folder: build
